fix(pf3): when isRequiered, asterisk is added to label
Hyperkid123/data-driven-forms pull request #35
Opened 2018-11-22 14:43 UTC by rvsia

When pf3 field gets isRequired then an asterisk is added to label

2018-11-22 15:06 UTC, Hyperkid123 requested changes

2018-11-22 15:06 UTC, Hyperkid123 commented on src/pf-3-form-fields/form-fields.js
> +            { !hideLabel && (rest.isRequired ? __(label).concat(' *') : __(label)) }
For pf3 This should look like this: https://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/

2018-11-22 15:12 UTC, Hyperkid123 commented
@rvsia also there is a another component at `pf3-form-fields/multiple-choice-list`

2018-11-23 11:01 UTC, rvsia commented
@Hyperkid123 the multiselect doesn't wotk. Did the styling changes broke it or is it intended to not work?

2018-11-23 11:04 UTC, Hyperkid123 commented
@rvsia i know i am doing PR for that right now

2018-11-26 08:50 UTC, rvsia commented
OLD REPO -> CLOSED

2018-11-26 08:50 UTC, closed without merging